name: Run App Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
        id: node

      - name: Install Dependencies
        run: npm ci
      
      - name: Test
        run: npm run test
      
    